//
//  SignInWorker.swift
//  Tweetie
//
//  Created by Rebecca Duhard on 9/24/16.
//  Copyright (c) 2016 Rebecca. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SignInWorker
{
  // MARK: Business Logic
  
  func signInUser()
  {
    // NOTE: Do the work
  }
}
